// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.0
// source: proto/clothes.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateClothRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClothName string `protobuf:"bytes,1,opt,name=cloth_name,json=clothName,proto3" json:"cloth_name,omitempty"`
	ClothCost int32  `protobuf:"varint,2,opt,name=cloth_cost,json=clothCost,proto3" json:"cloth_cost,omitempty"`
	ClothSize string `protobuf:"bytes,3,opt,name=cloth_size,json=clothSize,proto3" json:"cloth_size,omitempty"`
}

func (x *CreateClothRequest) Reset() {
	*x = CreateClothRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_clothes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateClothRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClothRequest) ProtoMessage() {}

func (x *CreateClothRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clothes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClothRequest.ProtoReflect.Descriptor instead.
func (*CreateClothRequest) Descriptor() ([]byte, []int) {
	return file_proto_clothes_proto_rawDescGZIP(), []int{0}
}

func (x *CreateClothRequest) GetClothName() string {
	if x != nil {
		return x.ClothName
	}
	return ""
}

func (x *CreateClothRequest) GetClothCost() int32 {
	if x != nil {
		return x.ClothCost
	}
	return 0
}

func (x *CreateClothRequest) GetClothSize() string {
	if x != nil {
		return x.ClothSize
	}
	return ""
}

type CreateClothResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateClothResponse) Reset() {
	*x = CreateClothResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_clothes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateClothResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClothResponse) ProtoMessage() {}

func (x *CreateClothResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clothes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClothResponse.ProtoReflect.Descriptor instead.
func (*CreateClothResponse) Descriptor() ([]byte, []int) {
	return file_proto_clothes_proto_rawDescGZIP(), []int{1}
}

func (x *CreateClothResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetClothRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetClothRequest) Reset() {
	*x = GetClothRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_clothes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetClothRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClothRequest) ProtoMessage() {}

func (x *GetClothRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clothes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClothRequest.ProtoReflect.Descriptor instead.
func (*GetClothRequest) Descriptor() ([]byte, []int) {
	return file_proto_clothes_proto_rawDescGZIP(), []int{2}
}

func (x *GetClothRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetClothResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ClothName string `protobuf:"bytes,2,opt,name=cloth_name,json=clothName,proto3" json:"cloth_name,omitempty"`
	ClothCost int32  `protobuf:"varint,3,opt,name=cloth_cost,json=clothCost,proto3" json:"cloth_cost,omitempty"`
	ClothSize string `protobuf:"bytes,4,opt,name=cloth_size,json=clothSize,proto3" json:"cloth_size,omitempty"`
	CreatedAt string `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt string `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Version   int32  `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *GetClothResponse) Reset() {
	*x = GetClothResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_clothes_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetClothResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClothResponse) ProtoMessage() {}

func (x *GetClothResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clothes_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClothResponse.ProtoReflect.Descriptor instead.
func (*GetClothResponse) Descriptor() ([]byte, []int) {
	return file_proto_clothes_proto_rawDescGZIP(), []int{3}
}

func (x *GetClothResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetClothResponse) GetClothName() string {
	if x != nil {
		return x.ClothName
	}
	return ""
}

func (x *GetClothResponse) GetClothCost() int32 {
	if x != nil {
		return x.ClothCost
	}
	return 0
}

func (x *GetClothResponse) GetClothSize() string {
	if x != nil {
		return x.ClothSize
	}
	return ""
}

func (x *GetClothResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetClothResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *GetClothResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type EditClothRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ClothName string `protobuf:"bytes,2,opt,name=cloth_name,json=clothName,proto3" json:"cloth_name,omitempty"`
	ClothCost int32  `protobuf:"varint,3,opt,name=cloth_cost,json=clothCost,proto3" json:"cloth_cost,omitempty"`
	ClothSize string `protobuf:"bytes,4,opt,name=cloth_size,json=clothSize,proto3" json:"cloth_size,omitempty"`
}

func (x *EditClothRequest) Reset() {
	*x = EditClothRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_clothes_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditClothRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditClothRequest) ProtoMessage() {}

func (x *EditClothRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clothes_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditClothRequest.ProtoReflect.Descriptor instead.
func (*EditClothRequest) Descriptor() ([]byte, []int) {
	return file_proto_clothes_proto_rawDescGZIP(), []int{4}
}

func (x *EditClothRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EditClothRequest) GetClothName() string {
	if x != nil {
		return x.ClothName
	}
	return ""
}

func (x *EditClothRequest) GetClothCost() int32 {
	if x != nil {
		return x.ClothCost
	}
	return 0
}

func (x *EditClothRequest) GetClothSize() string {
	if x != nil {
		return x.ClothSize
	}
	return ""
}

type EditClothResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *EditClothResponse) Reset() {
	*x = EditClothResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_clothes_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditClothResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditClothResponse) ProtoMessage() {}

func (x *EditClothResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clothes_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditClothResponse.ProtoReflect.Descriptor instead.
func (*EditClothResponse) Descriptor() ([]byte, []int) {
	return file_proto_clothes_proto_rawDescGZIP(), []int{5}
}

func (x *EditClothResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteClothRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteClothRequest) Reset() {
	*x = DeleteClothRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_clothes_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteClothRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClothRequest) ProtoMessage() {}

func (x *DeleteClothRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clothes_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClothRequest.ProtoReflect.Descriptor instead.
func (*DeleteClothRequest) Descriptor() ([]byte, []int) {
	return file_proto_clothes_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteClothRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteClothResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteClothResponse) Reset() {
	*x = DeleteClothResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_clothes_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteClothResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClothResponse) ProtoMessage() {}

func (x *DeleteClothResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clothes_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClothResponse.ProtoReflect.Descriptor instead.
func (*DeleteClothResponse) Descriptor() ([]byte, []int) {
	return file_proto_clothes_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteClothResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListClothesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClothName string `protobuf:"bytes,1,opt,name=cloth_name,json=clothName,proto3" json:"cloth_name,omitempty"`
	ClothSize string `protobuf:"bytes,2,opt,name=cloth_size,json=clothSize,proto3" json:"cloth_size,omitempty"`
	Page      int32  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize  int32  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Sort      string `protobuf:"bytes,5,opt,name=sort,proto3" json:"sort,omitempty"`
}

func (x *ListClothesRequest) Reset() {
	*x = ListClothesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_clothes_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListClothesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClothesRequest) ProtoMessage() {}

func (x *ListClothesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clothes_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClothesRequest.ProtoReflect.Descriptor instead.
func (*ListClothesRequest) Descriptor() ([]byte, []int) {
	return file_proto_clothes_proto_rawDescGZIP(), []int{8}
}

func (x *ListClothesRequest) GetClothName() string {
	if x != nil {
		return x.ClothName
	}
	return ""
}

func (x *ListClothesRequest) GetClothSize() string {
	if x != nil {
		return x.ClothSize
	}
	return ""
}

func (x *ListClothesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListClothesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListClothesRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

type ListClothesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClotheList []*Cloth `protobuf:"bytes,1,rep,name=clothe_list,json=clotheList,proto3" json:"clothe_list,omitempty"`
}

func (x *ListClothesResponse) Reset() {
	*x = ListClothesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_clothes_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListClothesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClothesResponse) ProtoMessage() {}

func (x *ListClothesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clothes_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClothesResponse.ProtoReflect.Descriptor instead.
func (*ListClothesResponse) Descriptor() ([]byte, []int) {
	return file_proto_clothes_proto_rawDescGZIP(), []int{9}
}

func (x *ListClothesResponse) GetClotheList() []*Cloth {
	if x != nil {
		return x.ClotheList
	}
	return nil
}

type Cloth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ClothName string `protobuf:"bytes,2,opt,name=cloth_name,json=clothName,proto3" json:"cloth_name,omitempty"`
	ClothCost int32  `protobuf:"varint,3,opt,name=cloth_cost,json=clothCost,proto3" json:"cloth_cost,omitempty"`
	ClothSize string `protobuf:"bytes,4,opt,name=cloth_size,json=clothSize,proto3" json:"cloth_size,omitempty"`
}

func (x *Cloth) Reset() {
	*x = Cloth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_clothes_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cloth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cloth) ProtoMessage() {}

func (x *Cloth) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clothes_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cloth.ProtoReflect.Descriptor instead.
func (*Cloth) Descriptor() ([]byte, []int) {
	return file_proto_clothes_proto_rawDescGZIP(), []int{10}
}

func (x *Cloth) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Cloth) GetClothName() string {
	if x != nil {
		return x.ClothName
	}
	return ""
}

func (x *Cloth) GetClothCost() int32 {
	if x != nil {
		return x.ClothCost
	}
	return 0
}

func (x *Cloth) GetClothSize() string {
	if x != nil {
		return x.ClothSize
	}
	return ""
}

var File_proto_clothes_proto protoreflect.FileDescriptor

var file_proto_clothes_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6c, 0x6f, 0x74, 0x68, 0x65, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x71, 0x0a, 0x12,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x6f, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x6f, 0x74, 0x68, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x6f, 0x74, 0x68, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x6f, 0x74, 0x68, 0x5f, 0x63, 0x6f, 0x73, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x6c, 0x6f, 0x74, 0x68, 0x43, 0x6f, 0x73, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x6f, 0x74, 0x68, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x6f, 0x74, 0x68, 0x53, 0x69, 0x7a, 0x65, 0x22,
	0x25, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x6f, 0x74, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x21, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x6f,
	0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0xd7, 0x01, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x43, 0x6c, 0x6f, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x63, 0x6c, 0x6f, 0x74, 0x68, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x6f, 0x74, 0x68, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x6c, 0x6f, 0x74, 0x68, 0x5f, 0x63, 0x6f, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x63, 0x6c, 0x6f, 0x74, 0x68, 0x43, 0x6f, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x63, 0x6c, 0x6f, 0x74, 0x68, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x6c, 0x6f, 0x74, 0x68, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x22, 0x7f, 0x0a, 0x10, 0x45, 0x64, 0x69, 0x74, 0x43, 0x6c, 0x6f, 0x74, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x6f, 0x74, 0x68,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x6f,
	0x74, 0x68, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x6f, 0x74, 0x68, 0x5f,
	0x63, 0x6f, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x6c, 0x6f, 0x74,
	0x68, 0x43, 0x6f, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x6f, 0x74, 0x68, 0x5f, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x6f, 0x74, 0x68,
	0x53, 0x69, 0x7a, 0x65, 0x22, 0x2d, 0x0a, 0x11, 0x45, 0x64, 0x69, 0x74, 0x43, 0x6c, 0x6f, 0x74,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x22, 0x24, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6c, 0x6f,
	0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2f, 0x0a, 0x13, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x43, 0x6c, 0x6f, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x97, 0x01, 0x0a, 0x12, 0x4c,
	0x69, 0x73, 0x74, 0x43, 0x6c, 0x6f, 0x74, 0x68, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x6f, 0x74, 0x68, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x6f, 0x74, 0x68, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x6f, 0x74, 0x68, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x6f, 0x74, 0x68, 0x53, 0x69, 0x7a, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x73, 0x6f, 0x72, 0x74, 0x22, 0x44, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6c, 0x6f, 0x74,
	0x68, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x0b, 0x63,
	0x6c, 0x6f, 0x74, 0x68, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x6f, 0x74, 0x68, 0x52, 0x0a,
	0x63, 0x6c, 0x6f, 0x74, 0x68, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x74, 0x0a, 0x05, 0x43, 0x6c,
	0x6f, 0x74, 0x68, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x6f, 0x74, 0x68, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x6f, 0x74, 0x68, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x6f, 0x74, 0x68, 0x5f, 0x63, 0x6f, 0x73, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x6c, 0x6f, 0x74, 0x68, 0x43, 0x6f, 0x73,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x6f, 0x74, 0x68, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x6f, 0x74, 0x68, 0x53, 0x69, 0x7a, 0x65,
	0x32, 0xdd, 0x02, 0x0a, 0x0c, 0x43, 0x6c, 0x6f, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x44, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x6f, 0x74, 0x68,
	0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43,
	0x6c, 0x6f, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x6f, 0x74, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x43, 0x6c,
	0x6f, 0x74, 0x68, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x43,
	0x6c, 0x6f, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x6f, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x09, 0x45, 0x64, 0x69, 0x74, 0x43, 0x6c, 0x6f, 0x74,
	0x68, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x43, 0x6c,
	0x6f, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x43, 0x6c, 0x6f, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6c,
	0x6f, 0x74, 0x68, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x43, 0x6c, 0x6f, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6c, 0x6f,
	0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0b, 0x4c, 0x69,
	0x73, 0x74, 0x43, 0x6c, 0x6f, 0x74, 0x68, 0x65, 0x73, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6c, 0x6f, 0x74, 0x68, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x43, 0x6c, 0x6f, 0x74, 0x68, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x61, 0x61, 0x74, 0x74, 0x65,
	0x7a, 0x75, 0x2f, 0x63, 0x6c, 0x6f, 0x74, 0x68, 0x65, 0x73, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_clothes_proto_rawDescOnce sync.Once
	file_proto_clothes_proto_rawDescData = file_proto_clothes_proto_rawDesc
)

func file_proto_clothes_proto_rawDescGZIP() []byte {
	file_proto_clothes_proto_rawDescOnce.Do(func() {
		file_proto_clothes_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_clothes_proto_rawDescData)
	})
	return file_proto_clothes_proto_rawDescData
}

var file_proto_clothes_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_clothes_proto_goTypes = []interface{}{
	(*CreateClothRequest)(nil),  // 0: proto.CreateClothRequest
	(*CreateClothResponse)(nil), // 1: proto.CreateClothResponse
	(*GetClothRequest)(nil),     // 2: proto.GetClothRequest
	(*GetClothResponse)(nil),    // 3: proto.GetClothResponse
	(*EditClothRequest)(nil),    // 4: proto.EditClothRequest
	(*EditClothResponse)(nil),   // 5: proto.EditClothResponse
	(*DeleteClothRequest)(nil),  // 6: proto.DeleteClothRequest
	(*DeleteClothResponse)(nil), // 7: proto.DeleteClothResponse
	(*ListClothesRequest)(nil),  // 8: proto.ListClothesRequest
	(*ListClothesResponse)(nil), // 9: proto.ListClothesResponse
	(*Cloth)(nil),               // 10: proto.Cloth
}
var file_proto_clothes_proto_depIdxs = []int32{
	10, // 0: proto.ListClothesResponse.clothe_list:type_name -> proto.Cloth
	0,  // 1: proto.ClothService.CreateCloth:input_type -> proto.CreateClothRequest
	2,  // 2: proto.ClothService.GetCloth:input_type -> proto.GetClothRequest
	4,  // 3: proto.ClothService.EditCloth:input_type -> proto.EditClothRequest
	6,  // 4: proto.ClothService.DeleteCloth:input_type -> proto.DeleteClothRequest
	8,  // 5: proto.ClothService.ListClothes:input_type -> proto.ListClothesRequest
	1,  // 6: proto.ClothService.CreateCloth:output_type -> proto.CreateClothResponse
	3,  // 7: proto.ClothService.GetCloth:output_type -> proto.GetClothResponse
	5,  // 8: proto.ClothService.EditCloth:output_type -> proto.EditClothResponse
	7,  // 9: proto.ClothService.DeleteCloth:output_type -> proto.DeleteClothResponse
	9,  // 10: proto.ClothService.ListClothes:output_type -> proto.ListClothesResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_clothes_proto_init() }
func file_proto_clothes_proto_init() {
	if File_proto_clothes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_clothes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateClothRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_clothes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateClothResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_clothes_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetClothRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_clothes_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetClothResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_clothes_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditClothRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_clothes_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditClothResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_clothes_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteClothRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_clothes_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteClothResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_clothes_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListClothesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_clothes_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListClothesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_clothes_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cloth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_clothes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_clothes_proto_goTypes,
		DependencyIndexes: file_proto_clothes_proto_depIdxs,
		MessageInfos:      file_proto_clothes_proto_msgTypes,
	}.Build()
	File_proto_clothes_proto = out.File
	file_proto_clothes_proto_rawDesc = nil
	file_proto_clothes_proto_goTypes = nil
	file_proto_clothes_proto_depIdxs = nil
}
